# Generated by Django 3.1.7 on 2021-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('userListed', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('description', models.TextField(default='No description provided.')),
                ('tags', models.JSONField()),
            ],
        ),
    ]
